### ISSUE TITLE
Design of Inline Relations

### ISSUE THREAD

**Issue by desi-bach** [whatwedo/CrudBundle#99]
## Is
Inline relations need improvement in design. E.g.: The table of the inline relation is currently cut off on the right and the left. 
![Screenshot 2022-08-12 at 11 05 18 copy](https://user-images.githubusercontent.com/102159086/184322533-62baf59f-14d1-45b7-8fe4-aa01788431ac.png)

## Should
Inline releations look better and no content or table outline disappears 

## Acceptance Criteria

- [ ] Inline releations look better and no content or table outline disappears

**Comment by marcwieland95** [comment]
This is fixed by refactoring the full basic layout template

**Comment by desi-bach** [comment]
> This is fixed by refactoring the full basic layout template

This issue is still not fixed. The vertical table outlines are not visible. 

![Screenshot 2022-09-22 at 08 55 41](https://user-images.githubusercontent.com/102159086/191678823-304b19b3-9677-4d88-bc1c-c73e9244c6a6.png)
